package api

import (
	"bytes"
	"crypto/ed25519"
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	blueruntime "github.com/ZabLaboratory/Blue/runtime/go"

	"github.com/ZabLaboratory/Orion/internal/attestation"
	"github.com/ZabLaboratory/Orion/internal/bluehost"
	"github.com/ZabLaboratory/Orion/internal/blueproject"
	"github.com/ZabLaboratory/Orion/internal/bluewire"
	"github.com/ZabLaboratory/Orion/internal/protocol"
	"github.com/ZabLaboratory/Orion/internal/providers"
)

// chatOverlayProgramFixture loads the ADR-BLUE-012 R6 §6.2 chat-driven
// blue.program.v1 fixture (Orion#181): a chat-driven scene reusing three
// chained pure computations — the Orion-side analogue of "reusing 3
// published blueprint-functions", since by the time a program reaches
// Orion it is already flat/compiled (Canvas/Blue own the authoring-time
// expansion, not Orion — issue #181 scope is adaptation/host/provider
// only):
//
//  1. core.data.get-field@1  — extract payload.message from the chat event
//  2. core.string.concat@1   — format it behind an "overlay" prefix
//  3. core.math.add@1        — accumulate a running chat_count
//
// Both results are stored via core.variable.set@1 into declared state
// outputs (overlay_message, chat_count) — the only mechanism that feeds
// StepResult.Outputs and therefore blueproject.Project/bluewire.Bridge
// (core.output@1 writes elsewhere and does NOT feed projection, see
// blue-runtime-go handlers.go:370-375).
//
// Unlike the hand-written fixture this replaces, these bytes are not
// authored here: they are regenerated by Blue's real, portable, deterministic
// compiler (ZabLaboratory/Blue src/blue_engine/program/compiler.py —
// ProgramCompiler/compile_program_bytes) from a realistic graph, in
// ZabLaboratory/Blue tests/test_orion_181_databound_fixture.py::
// test_emit_orion_181_chat_overlay_program_fixture, which regenerates and
// re-asserts this exact file. testdata/orion_181_chat_overlay_program.json
// is byte-identical to Blue's tests/contract/orion_181_chat_overlay_program.json
// (verified by Forge at authoring time; both sides must be regenerated
// together if the compiler's output shape ever changes). The entrypoint's
// platform/channel/event_type ("twitch"/"zablab_chat"/"chat_message") use
// the same casefold-then-validate convention as
// providers.CanonicalPlatformLeaf, so the leaf this test injects on always
// matches the one baked into the fixture by the compiler.
func chatOverlayProgramFixture(t *testing.T) []byte {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("testdata", "orion_181_chat_overlay_program.json"))
	if err != nil {
		t.Fatalf("read chat-overlay program fixture: %v", err)
	}
	return data
}

// chatMessageEvent builds a blue.runtime.event.v1 envelope for one chat
// message, using the same quasar.<platform>.<channel> / quasar.<platform>.
// <type> convention internal/providers.platformLeafFromEvent derives a
// canonical leaf from (mirrors internal/providers/events_test.go's
// platformEvent helper).
func chatMessageEvent(t *testing.T, eventID string, sequence uint64, message string) []byte {
	t.Helper()
	data, err := providers.BuildEvent(
		eventID, "quasar.twitch.zablab_chat", "quasar.twitch.chat_message", "corr-181",
		sequence, 1786500000000+int64(sequence),
		map[string]any{"message": message},
	)
	if err != nil {
		t.Fatalf("BuildEvent(%s): %v", eventID, err)
	}
	return data
}

// capturingMirror records every Delta bluewire.Bridge forwards, in order —
// the observation seam for asserting the actual PROJECTED EFFECT of chat
// injection, not merely that injection was accepted.
type capturingMirror struct {
	mu     sync.Mutex
	deltas []*protocol.Delta
}

func (m *capturingMirror) Forward(msg any) {
	m.mu.Lock()
	defer m.mu.Unlock()
	if d, ok := msg.(*protocol.Delta); ok {
		m.deltas = append(m.deltas, d)
	}
}

func (m *capturingMirror) snapshot() []*protocol.Delta {
	m.mu.Lock()
	defer m.mu.Unlock()
	out := make([]*protocol.Delta, len(m.deltas))
	copy(out, m.deltas)
	return out
}

func patchValue(t *testing.T, delta *protocol.Delta, path string) json.RawMessage {
	t.Helper()
	for _, p := range delta.Patches {
		if p.Path == path {
			return p.Value
		}
	}
	t.Fatalf("delta has no patch for path %q (patches: %+v)", path, delta.Patches)
	return nil
}

// TestChatDrivenScene_InjectionOrderingIdempotenceProjection is Orion#181
// (ADR-BLUE-012 R6 §§4.3,6.4; B8,B18): a chat-driven scene, taken on-air
// through the REAL postSceneIntent handler (attestation verify, workload
// fetch, digest cross-check, bluehost.Host.Take — the exact path production
// uses), then driven exactly the way a live Quasar transport would drive it
// (internal/providers.InjectActivePlatform — Orion#332's ingress adapter) and
// projected through a REAL bluewire.Bridge/blueproject.Project onto an
// observed mirror. It proves the EFFECT, not just that a call returned
// without error:
//   - injection: an accepted event actually reaches the running instance
//     and changes its state (asserted via the projected patch content)
//   - ordering: a sequence-gap event is rejected AND produces no projection;
//     two in-order events accumulate a correct running counter
//   - idempotence: a duplicate event_id (ingress layer) and a replayed
//     scene-intent request (same idempotency_key, HTTP layer) each produce
//     no re-execution and no new/corrupting projection — critically, a
//     scene-intent replay must NOT reset the ingress ordering state
//     (providers.ResetActiveIngress only fires on a FRESH Take)
//   - projection: every accepted, state-changing event is observable on the
//     mirror as a Delta carrying the expected overlay_message/chat_count
func TestChatDrivenScene_InjectionOrderingIdempotenceProjection(t *testing.T) {
	leaf, err := providers.CanonicalPlatformLeaf("twitch", "zablab_chat", "chat_message")
	if err != nil {
		t.Fatalf("CanonicalPlatformLeaf: %v", err)
	}
	program := chatOverlayProgramFixture(t)

	pub, priv, _ := ed25519.GenerateKey(nil)
	envelope, digest := canvasEnvelope(program)
	now := time.Now()
	ref := signedRef(t, priv, "canvas-key-181", attestation.ActionTakeOnAir, now, "scene-1", digest)

	wl := &fakeWorkload{body: envelope}
	host := bluehost.NewHost()
	t.Cleanup(func() { _ = host.Release(bluehost.SlotOnAir, "test-cleanup") })

	deps := SceneIntentDeps{
		Trust:         attestation.TrustSet{"canvas-key-181": pub},
		LocatorPrefix: "scenes/",
		OwnerID:       "owner-1",
		TenantID:      "tenant-1",
		Workload:      wl,
		Host:          host,
		Idempotency:   NewIdempotencyCache(),
	}

	send := func(idempotencyKey string) *httptest.ResponseRecorder {
		body, _ := json.Marshal(sceneIntentRequest{
			IntentID: "intent-181", IdempotencyKey: idempotencyKey, StreamID: "stream-1",
			Action: string(attestation.ActionTakeOnAir), ResolvedSceneRef: ref,
		})
		req := httptest.NewRequest(http.MethodPost, "/api/v1/host/scene-intent", bytes.NewReader(body))
		req.Header.Set("X-Authenticated-User", "operator-1")
		req.Header.Set("X-Authenticated-Role", "operator")
		req.Header.Set(authContextHeader, "opaque-ticket")
		rec := httptest.NewRecorder()
		postSceneIntent(deps)(rec, req)
		return rec
	}

	if rec := send("idem-181"); rec.Code != http.StatusOK {
		t.Fatalf("take-on-air: expected 200, got %d: %s", rec.Code, rec.Body.String())
	}
	// Host.Take stores the aligned serving version (M6, #398):
	// claims.ArtifactSetDigest — signedRef's fixed "bbb..." placeholder,
	// not claims.SceneDigest and not the program's own digest.
	wantVersion := "sha256:" + strings.Repeat("b", 64)
	if got := host.Digest(bluehost.SlotOnAir); got != wantVersion {
		t.Fatalf("expected on-air serving version %q, got %q", wantVersion, got)
	}

	// A bridge built directly (bluewire.NewBridge), stepped synchronously —
	// the same production type postSceneIntent's startBridge wires, just
	// driven deterministically instead of via its background goroutine, so
	// this test controls exactly when a tick happens relative to injection.
	mirror := &capturingMirror{}
	bridge := bluewire.NewBridge(host, bluehost.SlotOnAir, mirror, "scene-1", "sha256:"+strings.Repeat("a", 64), "ref-1", blueproject.TargetProgram, "rev-1", "corr-181")

	if err := bridge.TickOnce(0.1); err != nil {
		t.Fatalf("bridge.TickOnce (baseline): %v", err)
	}
	baseline := mirror.snapshot()
	if len(baseline) != 1 {
		t.Fatalf("expected exactly 1 baseline projection, got %d", len(baseline))
	}
	if got := string(patchValue(t, baseline[0], "overlay_message")); got != `""` {
		t.Fatalf("baseline overlay_message: got %s, want empty string", got)
	}
	if got := string(patchValue(t, baseline[0], "chat_count")); got != "0" {
		t.Fatalf("baseline chat_count: got %s, want 0", got)
	}

	// --- Injection + projection: first in-order chat event ---
	firstReceipt, err := providers.InjectActivePlatform(host, leaf, chatMessageEvent(t, "evt-1", 1, "gg"))
	if err != nil {
		t.Fatalf("InjectActivePlatform(evt-1): %v", err)
	}
	if firstReceipt.Status != "accepted" || firstReceipt.RuntimeSequence != 1 || firstReceipt.EventID != "evt-1" {
		t.Fatalf("unexpected first receipt: %+v", firstReceipt)
	}
	if err := bridge.TickOnce(0.1); err != nil {
		t.Fatalf("bridge.TickOnce (evt-1): %v", err)
	}
	afterFirst := mirror.snapshot()
	if len(afterFirst) != 2 {
		t.Fatalf("expected 2 projections after first event, got %d", len(afterFirst))
	}
	if got := string(patchValue(t, afterFirst[1], "overlay_message")); got != `"chat: gg"` {
		t.Fatalf("overlay_message after evt-1: got %s, want %q", got, `"chat: gg"`)
	}
	if got := string(patchValue(t, afterFirst[1], "chat_count")); got != "1" {
		t.Fatalf("chat_count after evt-1: got %s, want 1", got)
	}

	// --- Ordering: a second in-order event must accumulate, not overwrite ---
	secondReceipt, err := providers.InjectActivePlatform(host, leaf, chatMessageEvent(t, "evt-2", 2, "hello"))
	if err != nil {
		t.Fatalf("InjectActivePlatform(evt-2): %v", err)
	}
	if secondReceipt.RuntimeSequence != 2 {
		t.Fatalf("expected second receipt sequence 2, got %+v", secondReceipt)
	}
	if err := bridge.TickOnce(0.1); err != nil {
		t.Fatalf("bridge.TickOnce (evt-2): %v", err)
	}
	afterSecond := mirror.snapshot()
	if len(afterSecond) != 3 {
		t.Fatalf("expected 3 projections after second event, got %d", len(afterSecond))
	}
	if got := string(patchValue(t, afterSecond[2], "overlay_message")); got != `"chat: hello"` {
		t.Fatalf("overlay_message after evt-2: got %s, want %q", got, `"chat: hello"`)
	}
	if got := string(patchValue(t, afterSecond[2], "chat_count")); got != "2" {
		t.Fatalf("chat_count after evt-2: got %s (want 2 -- ordering broken if stale/overwritten)", got)
	}

	// --- Ordering: a sequence gap is rejected outright and never reaches
	// the runtime (no state change, therefore no new projection). ---
	if _, err := providers.InjectActivePlatform(host, leaf, chatMessageEvent(t, "evt-4", 4, "skip-ahead")); err == nil {
		t.Fatal("expected a sequence-gap rejection for source_sequence 4 after 2")
	} else {
		var runtimeErr *blueruntime.Error
		if !errors.As(err, &runtimeErr) || runtimeErr.Code != "EVENT_SEQUENCE_GAP" {
			t.Fatalf("expected EVENT_SEQUENCE_GAP, got %v", err)
		}
	}
	if err := bridge.TickOnce(0.1); err != nil {
		t.Fatalf("bridge.TickOnce (after rejected gap): %v", err)
	}
	if got := len(mirror.snapshot()); got != 3 {
		t.Fatalf("expected the rejected gap event to produce no new projection (still 3), got %d", got)
	}

	// --- Idempotence (ingress layer): replaying evt-1 returns the cached
	// receipt verbatim and does not re-run the program (counter stays put,
	// no new projection). ---
	replayReceipt, err := providers.InjectActivePlatform(host, leaf, chatMessageEvent(t, "evt-1", 1, "gg"))
	if err != nil {
		t.Fatalf("InjectActivePlatform(evt-1 replay): %v", err)
	}
	if replayReceipt != firstReceipt {
		t.Fatalf("expected the replay to return the identical original receipt, got %+v want %+v", replayReceipt, firstReceipt)
	}
	if err := bridge.TickOnce(0.1); err != nil {
		t.Fatalf("bridge.TickOnce (after ingress replay): %v", err)
	}
	if got := len(mirror.snapshot()); got != 3 {
		t.Fatalf("expected the idempotent ingress replay to produce no new projection (still 3, counter unchanged), got %d", got)
	}

	// --- Idempotence (scene-intent/HTTP layer): replaying the SAME
	// take-on-air intent must skip re-execution entirely (cached response,
	// no second Workload.Admit, no second Host.Take) -- and MUST NOT call
	// providers.ResetActiveIngress (that only fires on a fresh successful
	// Take), or the chat_count/dedup state accumulated above would be wiped.
	if rec := send("idem-181"); rec.Code != http.StatusOK {
		t.Fatalf("replayed take-on-air: expected 200, got %d: %s", rec.Code, rec.Body.String())
	}
	if wl.admitCalls != 1 {
		t.Fatalf("expected the scene-intent replay to skip re-execution (still 1 workload admission), got %d", wl.admitCalls)
	}
	thirdReceipt, err := providers.InjectActivePlatform(host, leaf, chatMessageEvent(t, "evt-3", 3, "still going"))
	if err != nil {
		t.Fatalf("InjectActivePlatform(evt-3, after scene-intent replay): %v", err)
	}
	if thirdReceipt.RuntimeSequence != 3 {
		t.Fatalf("expected sequence 3 to continue from 2 across the scene-intent replay (ingress ordering state was wrongly reset), got %+v", thirdReceipt)
	}
	if err := bridge.TickOnce(0.1); err != nil {
		t.Fatalf("bridge.TickOnce (evt-3): %v", err)
	}
	final := mirror.snapshot()
	if got := string(patchValue(t, final[len(final)-1], "chat_count")); got != "3" {
		t.Fatalf("chat_count after evt-3: got %s, want 3 (counter must survive an idempotent scene-intent replay)", got)
	}
	if got := string(patchValue(t, final[len(final)-1], "overlay_message")); got != `"chat: still going"` {
		t.Fatalf("overlay_message after evt-3: got %s, want %q", got, `"chat: still going"`)
	}
}
